# This workflow regularly performs a security audit of the bo dependencies

name: Scheduled security audit
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # This action is using cargo-audit to perform an audit for crates with security vulnerabilities.
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
