name: Cleanup S3

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  close_job:
    runs-on: ubuntu-latest
    steps:
    - name: "Remove the HTML coverage report for PR main branch from S3"
      uses: vitorsgomes/s3-rm-action@master
      with:
        args: --recursive
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: ${{ steps.coverage.outputs.report }}
        DEST_DIR: 'bo/${{ env.GITHUB_HEAD_REF }}'