name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  # Run cargo clippy to fish for code smells
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: Swatinem/rust-cache@v1  # cache crate builds between CI builds to make them faster
    - name: clippy
      run:  cargo clippy --all-targets --all-features -- -D warnings

  # Run cargo test
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: Swatinem/rust-cache@v1  # cache crate builds between CI builds to make them faster
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test --verbose
